Repository projectceladon/linux-intel-lts2022, pull requests merged in 2025-01, with the labels that each got.

#74 DRM: Add atomic commit log for resume
  drivers/acpi/sleep.c
  drivers/gpu/drm/drm_atomic_helper.c
  include/drm/drm_atomic.h
  include/linux/suspend.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#72 drm/virtio: Send flip event based on backend setting
  drivers/gpu/drm/virtio/virtgpu_debugfs.c
  drivers/gpu/drm/virtio/virtgpu_display.c
  drivers/gpu/drm/virtio/virtgpu_drv.c
  drivers/gpu/drm/virtio/virtgpu_drv.h
  drivers/gpu/drm/virtio/virtgpu_kms.c
  drivers/gpu/drm/virtio/virtgpu_vq.c
  include/uapi/linux/virtio_gpu.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#84 drm/virtio: Use flip sequence from virtio-GPU back-end
  drivers/gpu/drm/virtio/virtgpu_debugfs.c
  drivers/gpu/drm/virtio/virtgpu_display.c
  drivers/gpu/drm/virtio/virtgpu_drv.c
  drivers/gpu/drm/virtio/virtgpu_drv.h
  drivers/gpu/drm/virtio/virtgpu_kms.c
  drivers/gpu/drm/virtio/virtgpu_vq.c
  include/uapi/linux/virtio_gpu.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#86 Add S3 interface for virtio camera
  drivers/media/platform/virtio/virtio-camera.c
  include/uapi/linux/virtio_camera.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#85 DRM: Add the first atomic commit time for resume
  drivers/acpi/sleep.c
  drivers/gpu/drm/drm_atomic_helper.c
  include/drm/drm_atomic.h
  include/linux/suspend.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#90 drm: Check polling initialized before enabling in drm_helper_probe_si…
  drivers/gpu/drm/drm_probe_helper.c
Labels: Developer Approved, PR approved, Engineering Build Successful

#82 add support for VF LMEM type BLOB creation
  drivers/gpu/drm/virtio/virtgpu_drv.h
  drivers/gpu/drm/virtio/virtgpu_ioctl.c
  drivers/gpu/drm/virtio/virtgpu_kms.c
  drivers/gpu/drm/virtio/virtgpu_prime.c
  drivers/gpu/drm/virtio/virtgpu_vq.c
  include/uapi/drm/virtgpu_drm.h
  include/uapi/linux/virtio_gpu.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#88 Refine virtio camera inferface
  drivers/media/platform/virtio/virtio-camera.c
Labels: PR approved, Valid commit message

#91 drm/virtio: Protect cached vblank events with drm_event_lock
  drivers/gpu/drm/virtio/virtgpu_display.c
  drivers/gpu/drm/virtio/virtgpu_vq.c
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful

#95 Change virtiocamera device node name.
  drivers/media/platform/virtio/virtio-camera.c
  drivers/media/v4l2-core/v4l2-dev.c
  drivers/media/v4l2-core/v4l2-ioctl.c
  include/media/v4l2-dev.h
Labels: Developer Approved, PR approved, Valid commit message, Engineering Build Successful
